{
 "title": "Big Brother - Health Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dependency", "label": "Dependency", "query": "dependency_up" },
   { "name": "addr", "label": "Address", "query": "request_seconds_count:irate" },
   { "name": "type", "label": "Request Type", "query": "request_seconds_count:irate" },
   { "name": "prsn", "label": "Target", "query": "request_seconds_count:irate" }
  ]
 },
 "panels": [
  { "title": "Dependencies Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$dependency Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "dependency",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dependency_up{name=\"$dependency\", prsn=\"$prsn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum_over_time(request_seconds_sum:irate{type=\"$type\", prsn=\"$prsn\"}[1d])/sum_over_time(request_seconds_count:irate{type=\"$type\", prsn=\"$prsn\"}[1d]) > 0)",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Avg error rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(request_seconds_count:irate{status=~\"[4|5]..\", type=\"$type\", prsn=\"$prsn\"}[10m]))",
     "legendFormat": "Avg error rate"
    }
   ]
  },
  {
   "title": "Error proportion",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum_over_time(request_seconds_count:irate{status=~\"[4|5]..\",type=\"$type\", prsn=\"$prsn\"}[10m]))/sum(sum_over_time(request_seconds_count:irate{type=\"$type\", prsn=\"$prsn\"}[10m]))",
     "legendFormat": "Error proportion"
    }
   ]
  },
  {
   "title": "Top 10 Error rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10,\n  (sum(sum_over_time(request_seconds_count:irate{status!~\"2..\"}[10m])) by (addr))\n  /\n  (sum(sum_over_time(request_seconds_count:irate[10m])) by (addr))\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10,\n  (sum(sum_over_time(request_seconds_sum:irate[10m])) by (addr))\n  /\n  (sum(sum_over_time(request_seconds_count:irate[10m])) by (addr))\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Throughput",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(avg_over_time(request_seconds_count:irate{status!~\"2..\"}[10m])) by (addr)\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "title": "Per address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Throughput and Latency ($addr)",
   "type": "graph",
   "description": "Throughput and Latency of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "repeat": "addr",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Throughput"
    },
    {
     "expr": "sum(request_seconds_sum:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Throughput and Error rate ($addr)",
   "type": "graph",
   "description": "Throughput and Error rate of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "repeat": "addr",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Throughput"
    },
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\", status!~\"2..\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latency and Error rate ($addr)",
   "type": "graph",
   "description": "Latency and Error rate of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "repeat": "addr",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_sum:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Latency"
    },
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\", status!~\"2..\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\", prsn=\"$prsn\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Error rate"
    }
   ]
  }
 ]
}